### ISSUE TITLE
add a pre-compiler

### ISSUE THREAD

**Issue by marius851000** [EddyK28/PMD-Lua-Mod-Loader#2]
I suggest to add a tool to "pre-compile" mods.
The problem with the actual method is that you can't dynamycilly enable the patching of a file.
for exemple if the A mod modify the message.bin ( or a graphic related ) file, and the user do not want this feeature, it should manualy modify the mod or delete the message.bin file. Also, if multiple optional mod modify this file, there is high risk of conflict.

an idea could be to create a program ( python, because I thing it's a 
good programming language or lua, because it can be integrated to the 
game if we figure how to access the file system of the 3ds ) which 
generate the romfs folder ( and maybe the exefs ). Here is my idea of 
algorithm.

1. create a render folder, containing the romfs and exefs folder
2. copy mods and the mod menu loader to the romfs folder.
3. read the setting of each mod.
4. list the list of modification to the romfs and exefs ( in mods 
setting )
5. order them in the order the mod should be applyed ( eg : First, 
create/clone the A file, them modify it, not the reverse )
6. apply modifications

A lot of this is inspired with my older mod manager :
https://framagit.org/marius851000/PSMD-mod-manager

I think I'll work on this this weekend, but I want to know do you think about this ( I still recommend dynamic patching whenever possible ).

**Comment by EddyK28** [comment]
That's somewhat outside the scope of this project.  This is meant just for loading purely Lua based "mods", not making modifications to existing RomFS files.  It's also extremely unlikely that the games themselves (let alone the Lua scripts) have the file access needed to make these types modifications.

However, a separate tool for this that can be used to install content mods and this Lua-Mod loader (and maybe manage it's mods too), would be great.  I have no desire to do this myself, but you're more than welcome to.

**Comment by marius851000** [comment]
Ok. I think I'll just integrate some compatibility of this mod in my mod manager. thank for answering.

**Comment by marius851000** [comment]
Just, maybe it has access to the filesystem, as super mystery dungeon can be used to lauch the homebrew laucher ( which at least need to be able to read to the filesystem ). This is called supermysterychunkhax ( used before i was able to use the r4 hack ).
